### ISSUE TITLE
Please regenerate https://github.com/eclipse-oomph/oomph.incubator/blob/master/maven/org.eclipse.oomph.maven.generator/report/platform/REPORT.md

### ISSUE THREAD

**Issue by akurtakov** [eclipse-oomph/oomph.incubator#2]

**Comment by akurtakov** [comment]
I got few fixes like mockito, bnd, bytebuddy so it would be nice to see new report. Is it auto generated regularly or you do it manually?

**Comment by merks** [comment]
I still do it manually.  This is updated now:

https://github.com/eclipse-oomph/oomph.incubator/blob/master/maven/org.eclipse.oomph.maven.generator/report/platform/REPORT.md

Just ping here and I'll update it then...

FYI, when I did a build after the regeneration, these Dash thing were done:

> [INFO] This content is either not correctly mapped by the system, or requires review.
> [INFO] A review is required for maven/mavencentral/org.bouncycastle/bcpkix-jdk18on/1.75.
> [INFO] A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9166 .
> [INFO] A review is required for maven/mavencentral/org.bouncycastle/bcprov-jdk18on/1.75.
> [INFO] A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9167 .
> [INFO] A review is required for maven/mavencentral/com.google.errorprone/error_prone_annotations/2.20.0.
> [INFO] A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9168 .
> [INFO] A review is required for maven/mavencentral/com.ibm.icu/icu4j/73.2.
> [INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9093 .
> [INFO] A review is required for maven/mavencentral/com.google.inject.extensions/guice-assistedinject/7.0.0.
> [INFO] A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9169 .
> [INFO] A review is required for maven/mavencentral/org.bouncycastle/bcutil-jdk18on/1.75.
> [INFO] A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9170 .
> [INFO] Summary file was written to: /home/jenkins/agent/workspace/simrel/simrel-maven/maven/target/dash/summary

**Comment by akurtakov** [comment]
Thanks.

**Comment by akurtakov** [comment]
Would you please regenerate.

**Comment by merks** [comment]
No.   👅   But I mean that in a lovely way because the report is now here in its new Orbit location:

https://github.com/eclipse-orbit/orbit-simrel/blob/main/report/maven-osgi/platform/REPORT.md

And I think it's up-to-date.
